### ISSUE TITLE
Check out pkg2appimage

### ISSUE THREAD

**Issue by probonopd** [ferion11/PyCharm_Appimage#1]
Not a bug but I thought you perhaps might be interested in `pkg2appimage`, especially https://github.com/AppImage/pkg2appimage/commit/3c3c138e80d47390bbadf309c023aec023d4dab5.

For example,

```
wget -c https://github.com/$(wget -q https://github.com/AppImage/pkg2appimage/releases -O - | grep "pkg2appimage-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
chmod +x ./pkg2appimage-*.AppImage
./pkg2appimage-*.AppImage PyCharm-Community
```

should work...

**Comment by ferion11** [comment]
Thank you. I know it doesn't use all the potential of AppImage, but this one here has the sole objective of saving disk space (one executable file of ~380MB is better than: one ~380MB from the linux distribution package + the uncompressed version to use ~700MB to more than 1GB to just one app). So I'm just packing it on AppImage, in a more educational way, like a step by step, without worrying about having fewer commands :)
